/**
 * ERKI DASHBOARD - DATABASE TYPES
 *
 * This file will be auto-generated by Supabase CLI.
 * For now, we're using a placeholder schema.
 *
 * After setting up Supabase, run:
 * npm run supabase:types
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          role: "admin" | "user";
          is_approved: boolean;
          avatar_url: string | null;
          full_name: string | null;
          r6_username: string | null;
          r6_platform: "pc" | "psn" | "xbl" | null;
          created_at: string;
          last_seen: string | null;
          updated_at: string | null;
        };
        Insert: {
          id: string;
          email: string;
          role?: "admin" | "user";
          is_approved?: boolean;
          avatar_url?: string | null;
          full_name?: string | null;
          r6_username?: string | null;
          r6_platform?: "pc" | "psn" | "xbl" | null;
          created_at?: string;
          last_seen?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          role?: "admin" | "user";
          is_approved?: boolean;
          avatar_url?: string | null;
          full_name?: string | null;
          r6_username?: string | null;
          r6_platform?: "pc" | "psn" | "xbl" | null;
          created_at?: string;
          last_seen?: string | null;
          updated_at?: string | null;
        };
      };
      r6_cache: {
        Row: {
          id: string;
          user_id: string;
          username: string;
          platform: "pc" | "psn" | "xbl";
          stats: Json;
          cached_at: string;
          expires_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          username: string;
          platform: "pc" | "psn" | "xbl";
          stats: Json;
          cached_at?: string;
          expires_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          username?: string;
          platform?: "pc" | "psn" | "xbl";
          stats?: Json;
          cached_at?: string;
          expires_at?: string;
        };
      };
    };
    Views: {
      pending_approvals: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          created_at: string;
        };
      };
    };
    Functions: {
      cleanup_expired_cache: {
        Args: Record<string, never>;
        Returns: number;
      };
    };
  };
}
